apiVersion: v1
kind: Service
metadata:
  name: sagarapp
spec:
  ports:
  - port: 31001
    nodePort: 31001
    protocol: TCP
    targetPort: nodejs-port
  selector: 
    app: helloworld
  type: NodePort

